# Project information
site_name: Ansible Workshop
site_author: Natron Tech GmbH
site_description: >-
  Documentation and guides for the Ansible Workshop by Natron Tech GmbH.

# Repository
repo_url: https://github.com/natrontech/workshop-ansible
repo_name: natrontech/workshop-ansible
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Natron Tech GmbH

# Page tree
nav:
  - Home: index.md
  - Ansible explained: 
    - explained/index.md
    - Concepts: explained/concepts.md
    - Files: explained/files.md
    - Running Playbooks: explained/running-playbooks.md
    - Indempotency: explained/indempotency.md
  - Setup:
    - setup/index.md
    - Development:
      - setup/dev/index.md
      - Control Node Setup: setup/dev/control-node.md
    - Production:
      - setup/prod/index.md
      - Control Node Setup: setup/prod/control-node.md
      - Directory Structure: setup/prod/directory-structure.md
  - Basics:
    - basics/index.md
    - Inventory:
      - Creating: basics/inventory/create-inventory.md
      - Variables: basics/inventory/variables.md
      - Magic Variables: basics/inventory/magic-vars.md
      - Validating: basics/inventory/validate-inventory.md
    - Tasks:
      - Running your first tasks: basics/tasks/first-task.md
      - Gather facts: basics/tasks/gather-facts.md
      - Handlers: basics/tasks/handlers.md
    - Modules:
      - debug: basics/modules/debug.md
      - template: basics/modules/template.md
  - Advanced:
    - advanced/index.md
    - Linting:
      - TODO Ansible lint: advanced/linting/ansible-lint.md
    - CI/CD: 
      - TODO Gitlab CI: advanced/ci-cd/gitlab-ci.md
    - Various:
      - TODO Global vars: advanced/various/global-vars.md
      - TODO Loop unil when: advanced/various/loop-until-when.md
  - Examples:
    - examples/index.md

# Configuration
theme:
  favicon: assets/images/favicon.png
  logo: assets/images/favicon.png
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.prune
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Plugins
plugins:
  - search:
      lang: en

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/natrontech
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/natron-gmbh



# Markdown extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes