- name: restart docker-compose
  ansible.builtin.command:
    cmd: docker compose -f /data/docker-compose.yml up -d
  changed_when: true

- name: reboot
  ansible.builtin.reboot:
    reboot_timeout: 600
    msg: "Reboot initiated by Ansible for updates"
